version: '3'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3002:3002"
    volumes:
      - .:/app
  
  mysql:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_DATABASE: breizhsport
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./sql/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "3306:3306"
