version: '3'

services:
  web:
    container_name: Breizhsport-Produit
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3002:3002"
    volumes:
      - .:/app
    networks:
      - breizhsport-network
  
  mysql:
    container_name: Base-mysql
    image: mysql:latest
    restart: always
    environment:
      MYSQL_DATABASE: breizhsport
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./sql/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "3306:3306"
    networks:
      - breizhsport-network

networks:
  breizhsport-network:
    driver: bridge
